import Head from 'next/head'
import Banner from '../components/Banner'
import Header from '../components/Header'

export default function Home() {
  return (
    <div className='bg-gray-100'>
      <Head>
        <title>Amazon next.js</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/amazon.ico' />
      </Head>

      <Header />

      <main className='max-w-screen-2xl mx-auto'>
        {/* Banner */}
        <Banner />

        {/* ProductFeed */}
      </main>
    </div>
  )
}
